version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: RA6XdvZLNp
    ports:
      - "27017:27017"
    #volumes:
    #  - /tmp/mongo_data:/data/db